import {
  ProvisioningPdu,
  ProvisioningInvite,
  ProvisioningStart,
  ProvisioningPublicKey,
  ProvisioningConfirmation,
  ProvisioningRandom,
  ProvisioningData,
  encodeProvisioningPdu,
  decodeProvisioningPdu,
} from './pdu';
import {
  confirmationSalt,
  confirmationKey,
  confirmationValue,
  provisioningSalt,
  sessionKey,
  sessionNonce,
  deviceKey as deriveDeviceKey,
} from './crypto';
import { sharedSecret } from '../crypto/ecdh';
import { ccmEncrypt } from '../crypto/ccm';
import { assertRange, MAX_IV_INDEX } from '../packet/ranges';

/**
 * The provisioning state machine (Mesh Protocol v1.1, Section 5.4.2
 * "Provisioning behavior"): the PROVISIONER side only - this project's
 * design (docs/superpowers/specs/2026-10-06-ble-mesh-provisioner-design.md
 * in the homtelli project) has Homey provision bulbs, never be provisioned
 * itself, so there is no Provisionee half to build here. This module
 * decides which Provisioning PDU to send next, verifies the two the peer
 * sends back that this side can actually check (Public Key, Confirmation,
 * Random), and builds the final Provisioning Data block - it does not
 * transport bytes (that is the adapter's "transport" port, per the design
 * document) and it does not decide network/application keys or unicast
 * addresses (that is the caller's allocator); it only drives the exchange
 * using whatever the caller already decided and already generated.
 *
 * SCOPE: the no-OOB path only, same commitment `pdu.ts` already states.
 * Algorithm is always BTM_ECDH_P256_CMAC_AES128_AES_CCM (Table 5.29 value
 * 0x00) - the only one `provisioning/crypto.ts` implements - Authentication
 * Method is always No OOB (Table 5.31 value 0x00), and AuthValue is always
 * the fixed 128-bit all-zero value Section 5.4.2.4.1 defines for that
 * method ("the authentication value shall be set to
 * 0x00000000000000000000000000000000, which means it is not
 * authenticated"). A device whose Capabilities PDU cannot be satisfied by
 * this (Section 5.4.2.3's own rule, see `MANDATORY OOB REFUSAL` below, or a
 * device that does not even offer the one algorithm this project
 * implements) is reported as `'unsupported'`, never silently treated as
 * though it had asked for the no-OOB path it did not actually offer.
 *
 * KNOWN SPECIFICATION VIOLATION, DISCLOSED RATHER THAN FIXED: this module
 * selects BTM_ECDH_P256_CMAC_AES128_AES_CCM whenever a device offers it
 * (Table 5.21 bit 0), with no regard for whether the device also offers
 * BTM_ECDH_P256_HMAC_SHA256_AES_CCM (bit 1). Section 5.4.2.3 states "The
 * Provisioner shall not use BTM_ECDH_P256_CMAC_AES128_AES_CCM if another
 * algorithm is supported by the Provisionee", and separately, right after
 * Table 5.21 in Section 5.4.1.2, "The BTM_ECDH_P256_HMAC_SHA256_AES_CCM
 * bit of the Algorithms field shall be set to 1 by a Provisionee" - i.e.
 * every CONFORMING node is required to offer the stronger algorithm, so
 * this module's unconditional CMAC_AES128 choice violates that "shall
 * not" against any conforming node it ever provisions. This is unavoidable
 * given what `provisioning/crypto.ts` implements (CMAC_AES128 only - no
 * `k5`/`s2` for HMAC_SHA256, see that module's own header) and is
 * considered acceptable for this design's actual targets (three Tuya mesh
 * bulbs, not general-purpose conformance), but it is NOT acceptable to
 * leave this undiscovered until it shows up as a puzzling interop report
 * on real hardware - hence this note, not a fix.
 *
 * PURITY. Like `packet/reassembly.ts`, this module keeps nothing of its
 * own: no module-level binding, no timer, no clock, and - unlike a real
 * Provisioner - no random number generator either. The ephemeral ECDH key
 * pair and RandomProvisioner (Section 5.4.2.4.1: "a string of random bits
 * generated by the Provisioner's random number generator ... compatible
 * with the requirements in Volume 2, Part H, Section 2 of the Core
 * Specification") are INPUTS to `beginProvisioning`, supplied by the
 * caller, not generated here. This is not only for purity: it is what
 * makes the published Section 8.7/8.17.1 exchange replayable as a
 * known-answer test at all, because the sample fixes both values, and a
 * module that rolled its own randomness could only ever be tested against
 * itself.
 *
 * INPUT OWNERSHIP: because those inputs are the CALLER's, this module
 * COPIES every Buffer it is handed (`beginProvisioning` copies the ephemeral
 * key pair, RandomProvisioner and the NetKey, and rebuilds
 * `ProvisioningDataInput` as a fresh object) rather than retaining a
 * reference to it, and likewise never retains a view into an incoming PDU or
 * into a buffer it hands back in `send`. The rule this follows is the
 * project-wide one these modules already state for their own decoders
 * (`pdu.ts`'s "Every Buffer field returned is a COPY", `composition.ts`'s NO
 * BUFFER ALIASING note): a caller's buffer may be reused, overwritten or
 * zeroed the moment the call returns, and this module reads its inputs again
 * several `step` calls later - the ephemeral key pair in
 * `onCapabilities`/`onPublicKeyDevice`, RandomProvisioner in
 * `onConfirmationDevice`/`onRandomDevice`, the NetKey in `onRandomDevice`.
 * This is not hypothetical here: Section 5.4.2.3's "After the ECDHSecret is
 * computed, the Provisioner ... shall delete its private-public key pair",
 * quoted again at that call site below, is an instruction a conscientious
 * caller may well follow by zeroing the very pair it handed in - which, with
 * a retained reference, would silently change the ConfirmationProvisioner
 * this module sends and the device key it derives. `machine.test.ts` pins
 * each of these copies with its own mutate-the-caller's-buffer test.
 *
 * ONE NULLISH CONVENTION, same reasoning as `packet/reassembly.ts`'s own
 * header: there is no `null`/`undefined` anywhere in this module's own
 * surface. Every `ProvisioningState` - including the three terminal
 * phases, `'provisioned'`/`'unsupported'`/`'failed'` - is a concrete,
 * fully-formed value, and `step` accepts every phase its own return type
 * can produce, so a caller can always feed a previous result's `state`
 * straight back in without an adapter in between:
 *
 *     let { state, send } = beginProvisioning(input);
 *     // ... send `send` over the transport, wait for a reply ...
 *     ({ state, send } = step(state, replyBytes));
 *
 * `step` on a terminal state (`'provisioned'`/`'unsupported'`/`'failed'`)
 * is a deliberate no-op - the same `state` comes back unchanged and
 * `send` is empty - rather than a throw, because "the exchange already
 * ended" is foreseeable, ordinary caller behaviour (a transport adapter
 * that races a stray retransmission against the bearer closing, for
 * instance), not a programming mistake.
 *
 * DIRECTION AND ORDER (`pdu.ts`'s own module header transcribes this in
 * full; repeated here only as the one-line map this module's `step`
 * dispatch follows): Invite(P->D), Capabilities(D->P), Start(P->D), Public
 * Key(P->D then D->P), Confirmation(P->D then D->P), Random(P->D then
 * D->P), Data(P->D), Complete(D->P) - with a Failed PDU (D->P) able to
 * replace whatever the Provisionee was about to send, at any point.
 * `beginProvisioning` sends Invite; every other P->D send happens inside
 * `step`, triggered by the D->P PDU immediately before it in this order -
 * EXCEPT Start and Public Key(Provisioner), which Section 5.4.2.3 has the
 * Provisioner send back-to-back with no reply in between: "Once the
 * Provisioner has determined that it can provision the Provisionee, it
 * shall send a Provisioning Start PDU..." is immediately followed, for the
 * no-OOB-public-key path this module always takes, by "...the Provisioner
 * sets the Public Key field in the Provisioning Start PDU to zero and the
 * public keys are exchanged between the Provisioner and the Provisionee" -
 * with no Provisionee message of any kind in between. The worked sample
 * confirms this is really back-to-back on the wire, not only in prose:
 * Section 8.7.5 "PB-ADV Provisioning Start" is followed directly by
 * Section 8.7.6 "PB-ADV Provisioning Public Key (Provisioner)", with no
 * Provisionee-side subsection published between them. So the single
 * `step` call that processes the incoming Capabilities PDU returns BOTH
 * in its `send` array, in that order. This is the one point in the
 * exchange where `send` holds more than one PDU;
 * `beginProvisioning`'s own `Figure 5.15` prose ("Provisioning is
 * performed using a five-step process: beaconing, invitation, exchanging
 * public keys, authentication, and distribution of the provisioning
 * data") groups them the same way.
 *
 * WHAT MAKES A STEP FAIL, failure PDUs and reason codes (Section 5.4.4
 * "Provisioning errors", Table 5.41 "Provisioning error codes"): "When the
 * provisioning protocol fails for any reason, the Provisionee shall
 * permanently delete any stored details ... The provisioning protocol is
 * asymmetric when handling protocol errors. When the Provisioner
 * encounters an error other than a timeout in the provisioning protocol,
 * it shall immediately disconnect the provisioning bearer, providing the
 * Fail reason." The PROVISIONER does not send a Provisioning Failed PDU
 * for any of THESE errors (`pdu.ts`'s own DIRECTION table: Failed is
 * Provisionee -> Provisioner only, for every case this module itself
 * detects) - so a `'failed'` result from this module's own checks is
 * never itself a wire message; it is this module's own classification of
 * why it is refusing to continue, using Table 5.41's own named vocabulary
 * (`errorCode` plus `errorName`, via `provisioningErrorName` below)
 * because that vocabulary is what the specification already uses for
 * exactly these conditions, not because the Provisioner transmits it.
 * ONE exception exists, which this clockless module deliberately does not
 * implement: Section 5.4.4's own closing paragraph states that on the
 * provisioning TIMER's expiry specifically - unlike every other error -
 * "the Provisioner shall send a Provisioning Failed PDU, and the
 * Provisionee shall not send a Provisioning Failed PDU". Timeouts need a
 * clock, which is exactly why they are the adapter layer's job, not this
 * pure module's (see the PURITY note above) - but whoever owns that timer
 * next must know the Provisioner really does send Failed in that one
 * case, so the absolute "the Provisioner never sends Failed" is not
 * restated here. Three sources feed a `'failed'` result from this module:
 *
 *   1. The Provisionee's OWN Provisioning Failed PDU, reporting ITS error
 *      code verbatim. Section 5.4.1.10 is two sentences in total: "The
 *      Provisionee sends a Provisioning Failed PDU if it fails to process
 *      a received provisioning protocol PDU." - checked FIRST, before any
 *      phase-specific type check, in every handler below, because
 *      `pdu.ts`'s own DIRECTION table already establishes that a Failed
 *      PDU can replace whatever D->P message this phase was expecting,
 *      so receiving one here is never itself "unexpected".
 *   2. A PDU this module cannot even decode, or one that decodes but is
 *      not the type this phase expects - classified 0x01 "Invalid PDU" or
 *      0x03 "Unexpected PDU" respectively (see `decodeOrFail`/
 *      `unexpectedType` below). THIS is the "PDU arriving out of order"
 *      case: Section 5.4.4's asymmetric handling means the Provisioner's
 *      own answer to it is exactly the same as any other protocol error -
 *      stop, with a reason - not silently wait for the right PDU to show
 *      up later, which would leave a caller unable to tell a slow-but-
 *      healthy peer from one that has already gone wrong.
 *   3. A cryptographic check this module performs itself failing: an
 *      invalid or degenerate device public key (0x02 "Invalid Format",
 *      Section 5.4.2.3: "When the Provisioner receives an invalid public
 *      key or a public key that is equal to the Provisioner public key,
 *      then provisioning shall fail"), or a confirmation value that does
 *      not check out (0x04 "Confirmation Failed", Section 5.4.2.4.2 - two
 *      separate checks share this code: the one described below and the
 *      main one, `onRandomDevice`'s own recomputation).
 *
 * Section 5.4.2.4.2 also documents a cheap SANITY check this module
 * performs before anything else, once the Provisionee's Confirmation PDU
 * arrives: "the Provisioner ... shall compare the ConfirmationProvisioner
 * and the ConfirmationDevice values. ... If the values are equal, the
 * provisioning protocol shall fail" - the second ellipsis stands for the
 * source's own intervening "if not equal" bullet (the ordinary case,
 * handled below by sending RandomProvisioner), not for anything dropped
 * from the "equal" bullet itself. I.e. if the value just received is
 * byte-identical to the value THIS side already sent, something is badly
 * wrong (a reflection, or a peer that never used its own random number),
 * and this is cheap enough to check immediately rather than only
 * discovering it indirectly once RandomDevice fails to reproduce it.
 *
 * COMPARISONS ARE NOT CONSTANT-TIME (`Buffer.prototype.equals`, used for
 * every confirmation/public-key comparison in this module, is a plain
 * byte-by-byte comparison that returns as soon as it finds a mismatch).
 * That is not a defect for the no-OOB path this module implements: in
 * Section 5.4.2.4.1's own terms, AuthValue is the fixed public all-zero
 * value for No OOB, so neither compared confirmation value is derived
 * from a long-term secret a timing side-channel could leak - there is
 * nothing here for an attacker to learn bit-by-bit. A Static OOB path
 * would change that (AuthValue would then carry a real secret the static
 * OOB data protects), and WOULD need a constant-time comparison if ever
 * added - noted here so that addition does not silently inherit this
 * module's current, narrower justification for using a fast one.
 *
 * MANDATORY OOB REFUSAL (Section 5.4.2.3): "If bit 1 of the OOB Type
 * field of the Provisioning Capabilities PDU is set to 1 (Only OOB
 * authenticated provisioning supported) and any of the following
 * conditions is met: the Algorithm field ... is not set to
 * BTM_ECDH_P256_CMAC_AES128_AES_CCM and ... Authentication Method field
 * set to ... No OOB [or] the Algorithm field is set to
 * BTM_ECDH_P256_CMAC_AES128_AES_CCM [at all] ... the provisioning
 * protocol shall fail". Read together, a device with that bit set can
 * never legally be provisioned using BTM_ECDH_P256_CMAC_AES128_AES_CCM -
 * the only algorithm this project implements - regardless of
 * Authentication Method, so this module refuses as soon as it sees that
 * bit, before ever building a Start PDU. This is `'unsupported'`, not
 * `'failed'`: nothing has been sent, no protocol error has occurred, and
 * the design document is explicit that this is an open product decision -
 * "If one demands an out-of-band code, the wizard says so and we decide
 * then whether to add that path; it is not in this design."
 * (docs/superpowers/specs/2026-10-06-ble-mesh-provisioner-design.md) - not
 * a defect. The task brief's own restatement of that, "it must not be
 * silently treated as the no-out-of-band case", is why this gets its own
 * phase rather than being folded into `'failed'`. (An earlier revision of
 * this note quoted the brief's paraphrase of the design document - "the
 * wizard reports this and we decide later whether to add that path" - as
 * though it were the design document's own sentence, and compressed the
 * brief's "no-out-of-band" to "no-OOB" inside its quotation marks; both
 * are corrected above, and the conclusion they support is unchanged.) The
 * same `'unsupported'` phase (with
 * a different `reason`) also covers a device whose Capabilities PDU does
 * not offer BTM_ECDH_P256_CMAC_AES128_AES_CCM at all (Table 5.21 bit 0
 * clear) - this project has no other algorithm to fall back to (see
 * `provisioning/crypto.ts`'s own header), so that device cannot be
 * provisioned by this module either, for a different, equally mundane
 * reason.
 *
 * PROVISIONING DATA FIELD ENCODING (Section 5.4.2.5, Table 5.47
 * "Provisioning data format": Network Key (16) || Key Index (2) || Flags
 * (1) || IV Index (4) || Unicast Address (2), 25 octets total). Key
 * Index, IV Index and Unicast Address are encoded here as plain
 * big-endian multi-octet numeric values, per Section 3.1.1's general rule
 * for Provisioning ("For ... Provisioning, all multiple-octet numeric
 * values shall be sent in big-endian" - the same rule `pdu.ts` already
 * applies to the Provisioning PDU layer's own numeric fields) - NOT
 * Section 4.3.1.1's Figure 4.4/4.5 bit-packed key-index format, even
 * though Table 5.47's own Key Index row text cross-references that
 * section.
 *
 * WHY, PRECISELY: this is a LAYER split, not a single-vs-multiple-index
 * split. Section 3.1.1 states TWO separate blanket rules, for two
 * different layers: "For ... Provisioning, all multiple-octet numeric
 * values shall be sent in big-endian", and separately "For the access
 * layer and Foundation Models, all multiple-octet numeric values shall be
 * little-endian". Section 4.3.1.1's Figure 4.4/4.5 packing lives in
 * Chapter 4 (the access-layer/Foundation-Model chapter) and - covering
 * explicitly both the two-index case (Figure 4.4) AND the single-index
 * case (Figure 4.5: "To pack one key index into two octets, 8 LSbs of
 * first key index value are packed into the first octet, placing the
 * remaining 4 MSbs into 4 LSbs of the second octet, and the 4 MSbs of the
 * second octet shall be set to 0.") - IS that
 * layer's own little-endian representation of a 12-bit value, not a
 * separate "packing" convention layered on top of endianness (the
 * capitalisation of "one" in an earlier revision of this quotation was
 * this file's own emphasis, not the document's, and is removed - the
 * single-index coverage it was emphasising is stated plainly instead).
 * Table
 * 5.47's citation of it for Provisioning's OWN Key Index field imports
 * the wrong layer's convention.
 *
 * INDEPENDENTLY CHECKED, not merely inferred from one example: the
 * access layer's own published sample uses the OPPOSITE byte order from
 * Provisioning's. Section 8.3.6 "Message #6" (a Config AppKey Add) gives
 * NetKeyIndex=0x456, AppKeyIndex=0x123, and publishes the packed bytes as
 * `56 34 12` - which is exactly Figure 4.4's own recipe applied to those
 * two values (low byte of NetKeyIndex `56`; the next octet's low nibble
 * takes AppKeyIndex's low nibble `3` and its high nibble takes
 * NetKeyIndex's top nibble `4`, giving `34`; the remaining byte of
 * AppKeyIndex, `12`) - confirmed by hand computation against the
 * figure's own stated procedure, not merely copied from the sample.
 * Meanwhile the PROVISIONING Data sample (Section 8.7.12/8.17.1)
 * publishes its own single Key Index as `05 67`. Figure 4.5's packing
 * requires the second octet's top nibble to be zero ("the 4 MSbs of the
 * second octet shall be set to 0"); `0x67`'s top nibble is `0x6`, so this
 * sample does NOT follow Figure 4.5 - while it IS exactly a plain
 * big-endian 16-bit value (`0x0567`, whose top nibble is naturally `0`
 * for any value inside the 12-bit range Section 4.3.1.1 says global key
 * indexes occupy). Two contrasting published samples, each matching ITS
 * OWN layer's stated endianness rule and neither matching the other
 * layer's: that is the real reason, not the one originally written here
 * (which argued from single-vs-multiple-index count - wrong, since
 * Figure 4.5 already covers the single-index case explicitly, and was
 * corrected after review). A further, independent cross-check: this same
 * Provisioning Data plaintext (Key Index bytes included) is exactly what
 * `crypto/__tests__/ccm.test.ts` already encrypts and matches against the
 * published ciphertext/MIC - so the big-endian bytes read here are
 * confirmed to be the actual on-the-wire plaintext, not a transcription
 * slip. `MAX_KEY_INDEX` below still enforces the 12-bit domain limit
 * Section 4.3.1.1 states, independent of which encoding is used.
 */

// ===========================================================================
// Field widths and protocol-constant values.
// ===========================================================================

const PUBLIC_KEY_LENGTH = 64; // Table 5.36: Public Key X (32) || Public Key Y (32).
const PRIVATE_KEY_LENGTH = 32; // P-256 scalar, matches `crypto/ecdh.ts#generateKeyPair`.
const RANDOM_LENGTH = 16; // Section 5.4.2.4.1: RandomProvisioner/RandomDevice under BTM_ECDH_P256_CMAC_AES128_AES_CCM.
const CONFIRMATION_LENGTH = 16; // Section 5.4.2.4.1: ditto, for ConfirmationProvisioner/ConfirmationDevice.
const NET_KEY_LENGTH = 16; // Table 5.47: Network Key.
const DATA_MIC_LENGTH = 8; // Section 5.4.2.5: "The size of the Provisioning Data MIC is 8 octets."
const MAX_OCTET = 0xff; // 8 bits - Attention Duration, Flags.
const MAX_KEY_INDEX = 0x0fff; // 12 bits (Section 4.3.1.1: "Global key indexes are 12 bits long").
/**
 * Table 3.5 "16-bit address allocations": `0b0xxxxxxxxxxxxxxx (excluding
 * 0b0000000000000000)` is Unicast Address - 0x0001 to 0x7fff. The wider
 * range 0x8000-0xbfff is Virtual Address and 0xc000-0xffff is Group
 * Address (neither a legal "Unicast address of the primary element",
 * Table 5.47's own words for this field); 0x0000 itself is Unassigned
 * Address, not a node address at all.
 */
const MIN_UNICAST_ADDRESS = 0x0001;
const MAX_UNICAST_ADDRESS = 0x7fff;

/** Table 5.29: the only algorithm `provisioning/crypto.ts` implements. */
const ALGORITHM_CMAC_AES128 = 0x00;
/** Table 5.21 bit 0 (Provisioning Capabilities' Algorithms field): BTM_ECDH_P256_CMAC_AES128_AES_CCM support. */
const ALGORITHM_CMAC_AES128_BIT = 0x0001;
/** Table 5.30's own 0x00 row, "No OOB Public Key is used" - this design never uses an OOB-retrieved device public key. */
const PUBLIC_KEY_NOT_OOB = 0x00;
/** Table 5.31: Authentication Method value for "No OOB" - the only method this module uses. */
const AUTHENTICATION_METHOD_NO_OOB = 0x00;
/** Table 5.23 bit 1 (Provisioning Capabilities' OOB Type field): "Only OOB authenticated provisioning supported". */
const OOB_ONLY_AUTHENTICATED_BIT = 0x02;

/**
 * Section 5.4.2.4.1, "Authentication with No OOB": "the authentication
 * value shall be set to 0x00000000000000000000000000000000, which means
 * it is not authenticated" - the fixed AuthValue this module always uses,
 * since it implements the no-OOB path only.
 */
const NO_OOB_AUTH_VALUE = Buffer.alloc(16, 0);

/** Table 5.41 "Provisioning error codes", transcribed in full. */
const PROVISIONING_ERROR_NAMES: ReadonlyMap<number, string> = new Map([
  [0x00, 'Prohibited'],
  [0x01, 'Invalid PDU'],
  [0x02, 'Invalid Format'],
  [0x03, 'Unexpected PDU'],
  [0x04, 'Confirmation Failed'],
  [0x05, 'Out of Resources'],
  [0x06, 'Decryption Failed'],
  [0x07, 'Unexpected Error'],
  [0x08, 'Cannot Assign Addresses'],
  [0x09, 'Invalid Data'],
]);

/**
 * Table 5.41's own `Name` column for `errorCode` - `'RFU'` for 0x0A-0xFF
 * ("Reserved for Future Use", Table 5.41's own row for that whole range),
 * `'Unknown'` only for a value outside the single octet the Error Code
 * field actually has (`decodeProvisioningPdu` already guarantees this
 * never happens for a decoded Failed PDU, since it reads exactly one
 * octet; this module's OWN `errorCode` values, 0x00-0x09, are always
 * covered directly by the map above).
 */
export function provisioningErrorName(errorCode: number): string {
  const known = PROVISIONING_ERROR_NAMES.get(errorCode);
  if (known !== undefined) return known;
  return errorCode >= 0x0a && errorCode <= 0xff ? 'RFU' : 'Unknown';
}

// ===========================================================================
// Public input/state/result types.
// ===========================================================================

/** The ephemeral P-256 key pair this provisioning attempt uses - generated and owned by the caller (see the module header's PURITY note), matching `crypto/ecdh.ts#generateKeyPair`'s own return shape. */
export interface EphemeralKeyPair {
  readonly publicKey: Buffer;
  readonly privateKey: Buffer;
}

/** Table 5.47 "Provisioning data format" - the network membership this provisioning attempt hands to the new node, decided entirely by the caller (this module owns no key material, address allocator or network state of its own). */
export interface ProvisioningDataInput {
  /** NetKey, 16 octets. */
  readonly netKey: Buffer;
  /** Global NetKey Index, 12 bits (Section 4.3.1.1). */
  readonly netKeyIndex: number;
  /** Table 5.48 bitmask: bit 0 Key Refresh Flag, bit 1 IV Update Flag, bits 2-7 RFU. */
  readonly flags: number;
  /** Current IV Index, 32 bits. */
  readonly ivIndex: number;
  /** Unicast address to assign to the new node's primary element. */
  readonly unicastAddress: number;
}

/** `beginProvisioning`'s input: everything needed to send the first PDU (Invite) and to carry the exchange through to Provisioning Data, all caller-supplied per the module header's PURITY note. */
export interface BeginProvisioningInput {
  /** Provisioning Invite PDU's Attention Duration field, seconds (Table 5.18). */
  readonly attentionDuration: number;
  readonly ephemeralKeyPair: EphemeralKeyPair;
  /** RandomProvisioner (Section 5.4.2.4.1), 16 bytes. */
  readonly randomProvisioner: Buffer;
  readonly provisioningData: ProvisioningDataInput;
}

interface AwaitingCapabilitiesState {
  readonly phase: 'awaitingCapabilities';
  readonly inviteValue: Buffer;
  readonly ephemeralKeyPair: EphemeralKeyPair;
  readonly randomProvisioner: Buffer;
  readonly provisioningData: ProvisioningDataInput;
}

interface AwaitingPublicKeyDeviceState {
  readonly phase: 'awaitingPublicKeyDevice';
  readonly inviteValue: Buffer;
  readonly capabilitiesValue: Buffer;
  readonly startValue: Buffer;
  readonly ephemeralKeyPair: EphemeralKeyPair;
  readonly randomProvisioner: Buffer;
  readonly provisioningData: ProvisioningDataInput;
}

interface AwaitingConfirmationDeviceState {
  readonly phase: 'awaitingConfirmationDevice';
  readonly randomProvisioner: Buffer;
  readonly provisioningData: ProvisioningDataInput;
  readonly ecdhSecret: Buffer;
  readonly confirmationSaltValue: Buffer;
  readonly confirmationKeyValue: Buffer;
  /** ConfirmationProvisioner, already sent - kept only for the Section 5.4.2.4.2 "values are equal" sanity check against the device's Confirmation PDU. */
  readonly ownConfirmation: Buffer;
}

interface AwaitingRandomDeviceState {
  readonly phase: 'awaitingRandomDevice';
  readonly randomProvisioner: Buffer;
  readonly provisioningData: ProvisioningDataInput;
  readonly ecdhSecret: Buffer;
  readonly confirmationSaltValue: Buffer;
  readonly confirmationKeyValue: Buffer;
  /** ConfirmationDevice as received - not yet verified; `onRandomDevice` recomputes it from RandomDevice and compares. */
  readonly confirmationDevice: Buffer;
}

interface AwaitingCompleteState {
  readonly phase: 'awaitingComplete';
  readonly deviceKeyValue: Buffer;
}

interface ProvisionedState {
  readonly phase: 'provisioned';
  readonly deviceKey: Buffer;
}

interface UnsupportedState {
  readonly phase: 'unsupported';
  readonly reason: string;
}

interface FailedState {
  readonly phase: 'failed';
  readonly errorCode: number;
  readonly errorName: string;
  readonly reason: string;
}

/**
 * The caller-owned state value (see the module header's PURITY and ONE
 * NULLISH CONVENTION notes). `phase` is the discriminant; the three
 * terminal phases (`'provisioned'`, `'unsupported'`, `'failed'`) carry no
 * leftover key material or other secrets from earlier phases - once the
 * exchange is decided, there is nothing further for this module to do
 * with them.
 */
export type ProvisioningState =
  | AwaitingCapabilitiesState
  | AwaitingPublicKeyDeviceState
  | AwaitingConfirmationDeviceState
  | AwaitingRandomDeviceState
  | AwaitingCompleteState
  | ProvisionedState
  | UnsupportedState
  | FailedState;

/**
 * Both `beginProvisioning` and `step` return this same shape: the next
 * state, plus every PDU (wire bytes, ready for the transport port) this
 * side must now send, in order. `send` is most often one element; it is
 * two only for the Capabilities step (see the module header's DIRECTION
 * AND ORDER note) and empty for every terminal phase.
 */
export interface ProvisioningStepResult {
  readonly state: ProvisioningState;
  readonly send: readonly Buffer[];
}

// ===========================================================================
// Input validation helpers (caller mistakes - thrown, never a `'failed'`
// result; see `pdu.ts`/`crypto.ts`'s own helpers of the same shape).
// ===========================================================================

function assertBufferLength(field: string, value: Buffer, expected: number): void {
  if (value.length !== expected) {
    throw new Error(`provisioning machine field "${field}" must be ${expected} bytes, got ${value.length}`);
  }
}

/**
 * Table 3.5: a node's primary element address must be a Unicast Address,
 * 0x0001-0x7fff - narrower than `assertRange`'s plain bit-width check
 * (which would also accept 0x0000 Unassigned, and every Virtual/Group
 * address up to 0xffff). This is the ONE field in `ProvisioningDataInput`
 * with a semantic range narrower than its wire width; every other field
 * here is still only width-checked, matching this project's established
 * division of labour (`pdu.ts`'s own BIT-FIELD / NUMBER-FIELD WIDTH
 * CHECKS note) - unicast addressing is this module's own direct concern
 * (it is the thing being assigned), not a value merely passed through.
 */
function assertUnicastAddress(field: string, value: number): void {
  if (!Number.isInteger(value) || value < MIN_UNICAST_ADDRESS || value > MAX_UNICAST_ADDRESS) {
    throw new Error(
      `${field} must be a unicast address, an integer in [${MIN_UNICAST_ADDRESS}, ${MAX_UNICAST_ADDRESS}] (Table 3.5 - 0x0000 is Unassigned, 0x8000-0xffff is Virtual/Group), got ${value}`,
    );
  }
}

// ===========================================================================
// Shared result builders.
// ===========================================================================

function makeFailed(errorCode: number, reason: string): FailedState {
  return { phase: 'failed', errorCode, errorName: provisioningErrorName(errorCode), reason };
}

function unexpectedType(expectedLabel: string, actualType: string): FailedState {
  return makeFailed(0x03, `expected a ${expectedLabel} PDU but received a ${actualType} PDU`);
}

type DecodeOutcome = { readonly decoded: ProvisioningPdu } | { readonly failed: FailedState };

/**
 * Shared by every phase handler: decodes `pdu` and, before any
 * phase-specific type check, handles the two conditions that are never
 * "unexpected" no matter which phase this is (see the module header's
 * WHAT MAKES A STEP FAIL note, source 1 and the decode half of source 2) -
 * a Provisioning Failed PDU from the device, reported verbatim, and bytes
 * this project's codec cannot decode at all.
 */
function decodeOrFail(pdu: Buffer): DecodeOutcome {
  const decoded = decodeProvisioningPdu(pdu);
  if (decoded === null) {
    return {
      failed: makeFailed(
        0x01,
        'received bytes do not decode as a recognised Provisioning PDU (wrong length, non-zero Padding bits, or an unimplemented/unassigned Type)',
      ),
    };
  }
  if (decoded.type === 'failed') {
    const name = provisioningErrorName(decoded.errorCode);
    return {
      failed: makeFailed(
        decoded.errorCode,
        `device reported provisioning failure: ${name} (0x${decoded.errorCode.toString(16).padStart(2, '0')})`,
      ),
    };
  }
  return { decoded };
}

// ===========================================================================
// Provisioning Data field encoding (Table 5.47 - see the module header's
// PROVISIONING DATA FIELD ENCODING note).
// ===========================================================================

function encodeUInt16BE(value: number): Buffer {
  const buf = Buffer.alloc(2);
  buf.writeUInt16BE(value, 0);
  return buf;
}

function encodeUInt32BE(value: number): Buffer {
  const buf = Buffer.alloc(4);
  buf.writeUInt32BE(value, 0);
  return buf;
}

// ===========================================================================
// beginProvisioning: sends Invite, the exchange's one send with no
// incoming PDU to react to.
// ===========================================================================

export function beginProvisioning(input: BeginProvisioningInput): ProvisioningStepResult {
  assertRange('provisioning machine field "attentionDuration"', input.attentionDuration, MAX_OCTET);
  assertBufferLength('ephemeralKeyPair.publicKey', input.ephemeralKeyPair.publicKey, PUBLIC_KEY_LENGTH);
  assertBufferLength('ephemeralKeyPair.privateKey', input.ephemeralKeyPair.privateKey, PRIVATE_KEY_LENGTH);
  assertBufferLength('randomProvisioner', input.randomProvisioner, RANDOM_LENGTH);
  assertBufferLength('provisioningData.netKey', input.provisioningData.netKey, NET_KEY_LENGTH);
  assertRange('provisioning machine field "provisioningData.netKeyIndex"', input.provisioningData.netKeyIndex, MAX_KEY_INDEX);
  assertRange('provisioning machine field "provisioningData.flags"', input.provisioningData.flags, MAX_OCTET);
  assertRange('provisioning machine field "provisioningData.ivIndex"', input.provisioningData.ivIndex, MAX_IV_INDEX);
  assertUnicastAddress('provisioning machine field "provisioningData.unicastAddress"', input.provisioningData.unicastAddress);

  const invitePdu: ProvisioningInvite = { type: 'invite', attentionDuration: input.attentionDuration };
  const inviteBytes = encodeProvisioningPdu(invitePdu);

  // EVERY caller-owned input is COPIED here, not retained by reference (see
  // the module header's INPUT OWNERSHIP note). `input.ephemeralKeyPair`,
  // `input.randomProvisioner` and `input.provisioningData.netKey` are the
  // CALLER's buffers; the exchange reads all three again, several `step`
  // calls later (the key pair in `onCapabilities`/`onPublicKeyDevice`, the
  // random in `onConfirmationDevice`/`onRandomDevice`, the NetKey in
  // `onRandomDevice`'s Provisioning Data block), so a view into any of them
  // would let a mutation made after this call returns change what this
  // module later sends - and this module's own header quotes the very
  // instruction ("After the ECDHSecret is computed, the Provisioner ...
  // shall delete its private-public key pair") a caller might follow
  // literally by zeroing the pair it just handed in. `provisioningData`'s
  // numeric fields are copied for the same reason, into a fresh object: the
  // caller's own object is an ordinary mutable record to the caller,
  // whatever `readonly` says to a TypeScript consumer.
  const ephemeralKeyPair: EphemeralKeyPair = {
    publicKey: Buffer.from(input.ephemeralKeyPair.publicKey),
    privateKey: Buffer.from(input.ephemeralKeyPair.privateKey),
  };
  const randomProvisioner = Buffer.from(input.randomProvisioner);
  const provisioningData: ProvisioningDataInput = {
    netKey: Buffer.from(input.provisioningData.netKey),
    netKeyIndex: input.provisioningData.netKeyIndex,
    flags: input.provisioningData.flags,
    ivIndex: input.provisioningData.ivIndex,
    unicastAddress: input.provisioningData.unicastAddress,
  };

  const state: ProvisioningState = {
    phase: 'awaitingCapabilities',
    // Buffer.from(...) COPIES - `inviteBytes` itself is also handed to the
    // caller below (in `send`) to transmit, and a transport adapter is
    // free to reuse/zero a send buffer once it believes the bytes are on
    // the wire. A bare `.subarray(1)` would be a VIEW into that same
    // memory, so a later mutation of the sent buffer would silently
    // change `inviteValue` - and therefore every confirmationSalt
    // computed afterward - without this module doing anything wrong by
    // its own argument-mutation rule (it is the CALLER's buffer that
    // changed, after the call returned). Parameters only - Section
    // 5.4.2.4.1's "...PDUValue" excludes the Type octet.
    inviteValue: Buffer.from(inviteBytes.subarray(1)),
    ephemeralKeyPair,
    randomProvisioner,
    provisioningData,
  };
  return { state, send: [inviteBytes] };
}

// ===========================================================================
// step: dispatches to the phase-specific handler, or no-ops on a terminal
// phase (see the module header's ONE NULLISH CONVENTION note).
// ===========================================================================

export function step(state: ProvisioningState, pdu: Buffer): ProvisioningStepResult {
  switch (state.phase) {
    case 'awaitingCapabilities':
      return onCapabilities(state, pdu);
    case 'awaitingPublicKeyDevice':
      return onPublicKeyDevice(state, pdu);
    case 'awaitingConfirmationDevice':
      return onConfirmationDevice(state, pdu);
    case 'awaitingRandomDevice':
      return onRandomDevice(state, pdu);
    case 'awaitingComplete':
      return onComplete(state, pdu);
    case 'provisioned':
    case 'unsupported':
    case 'failed':
      return { state, send: [] };
  }
}

// ===========================================================================
// Phase handlers, in wire order.
// ===========================================================================

function onCapabilities(state: AwaitingCapabilitiesState, pdu: Buffer): ProvisioningStepResult {
  const outcome = decodeOrFail(pdu);
  if ('failed' in outcome) return { state: outcome.failed, send: [] };
  const decoded = outcome.decoded;
  if (decoded.type !== 'capabilities') {
    return { state: unexpectedType('Capabilities', decoded.type), send: [] };
  }

  if ((decoded.algorithms & ALGORITHM_CMAC_AES128_BIT) === 0) {
    return {
      state: {
        phase: 'unsupported',
        reason: `device Capabilities does not offer BTM_ECDH_P256_CMAC_AES128_AES_CCM (Table 5.21 bit 0) - the only algorithm this project implements (algorithms=0x${decoded.algorithms.toString(16).padStart(4, '0')})`,
      },
      send: [],
    };
  }
  if ((decoded.oobType & OOB_ONLY_AUTHENTICATED_BIT) !== 0) {
    return {
      state: {
        phase: 'unsupported',
        reason:
          'device Capabilities requires OOB-authenticated provisioning (Table 5.23 bit 1 set); this design implements the no-OOB path only and decides later whether to add an OOB path (docs/superpowers/specs/2026-10-06-ble-mesh-provisioner-design.md)',
      },
      send: [],
    };
  }

  // Buffer.from(...) COPIES - `pdu` is the CALLER's incoming-PDU buffer
  // (e.g. a GATT receive scratch buffer a real adapter reuses for the
  // next notification), not this module's own. A bare `.subarray(1)`
  // would keep a VIEW into that buffer in `capabilitiesValue`, which is
  // read again much later (by `confirmationSalt` in `onPublicKeyDevice`)
  // - long after the caller could have overwritten it with the next
  // incoming PDU's bytes.
  const capabilitiesValue = Buffer.from(pdu.subarray(1));

  const startPdu: ProvisioningStart = {
    type: 'start',
    algorithm: ALGORITHM_CMAC_AES128,
    publicKey: PUBLIC_KEY_NOT_OOB,
    authenticationMethod: AUTHENTICATION_METHOD_NO_OOB,
    authenticationAction: 0,
    authenticationSize: 0,
  };
  const startBytes = encodeProvisioningPdu(startPdu);

  // BELT AND BRACES, measured: unlike the three copies around it, reverting
  // these two to bare `.subarray` views changes NO observable behaviour and
  // no test can catch it, because `encodeProvisioningPdu` builds its output
  // with `Buffer.concat`, which already copies - so the PDU handed to the
  // caller never shares memory with `state.ephemeralKeyPair.publicKey`
  // whether these copies are here or not. They are kept so that this
  // module's own `ProvisioningPublicKey` value owns its bytes regardless of
  // what the encoder happens to do with them, but do not read them as the
  // thing that protects the stored key pair; that is the copy
  // `beginProvisioning` makes (see the module header's INPUT OWNERSHIP note),
  // which IS pinned by its own test.
  const publicKeyPdu: ProvisioningPublicKey = {
    type: 'publicKey',
    publicKeyX: Buffer.from(state.ephemeralKeyPair.publicKey.subarray(0, 32)),
    publicKeyY: Buffer.from(state.ephemeralKeyPair.publicKey.subarray(32, 64)),
  };
  const publicKeyBytes = encodeProvisioningPdu(publicKeyPdu);

  const nextState: AwaitingPublicKeyDeviceState = {
    phase: 'awaitingPublicKeyDevice',
    inviteValue: state.inviteValue,
    capabilitiesValue,
    // Buffer.from(...) COPIES - same reasoning as `inviteValue` above:
    // `startBytes` is also handed to the caller to send (in this same
    // step's `send` array), so a view into it is not safe to keep.
    startValue: Buffer.from(startBytes.subarray(1)),
    ephemeralKeyPair: state.ephemeralKeyPair,
    randomProvisioner: state.randomProvisioner,
    provisioningData: state.provisioningData,
  };
  return { state: nextState, send: [startBytes, publicKeyBytes] };
}

function onPublicKeyDevice(state: AwaitingPublicKeyDeviceState, pdu: Buffer): ProvisioningStepResult {
  const outcome = decodeOrFail(pdu);
  if ('failed' in outcome) return { state: outcome.failed, send: [] };
  const decoded = outcome.decoded;
  if (decoded.type !== 'publicKey') {
    return { state: unexpectedType('Public Key', decoded.type), send: [] };
  }

  const publicKeyDevice = Buffer.concat([decoded.publicKeyX, decoded.publicKeyY]);

  // Section 5.4.2.3: "When the Provisioner receives ... a public key that
  // is equal to the Provisioner public key, then provisioning shall fail."
  if (publicKeyDevice.equals(state.ephemeralKeyPair.publicKey)) {
    return {
      state: makeFailed(0x02, "device's Public Key is identical to the provisioner's own ephemeral public key (Section 5.4.2.3)"),
      send: [],
    };
  }

  let ecdhSecret: Buffer;
  try {
    ecdhSecret = sharedSecret(state.ephemeralKeyPair.privateKey, publicKeyDevice);
  } catch (err) {
    // Section 5.4.2.3: "The Provisioner and the Provisionee shall check
    // whether the public key provided by the peer device ... is valid";
    // an invalid point is foreign/peer data, not a caller mistake, so it
    // becomes a 'failed' result rather than propagating Node's own
    // exception. Any OTHER error here is this module's own caller's
    // mistake (e.g. a corrupt ephemeralKeyPair.privateKey already past
    // `beginProvisioning`'s length check) and must not be masked.
    const code = (err as NodeJS.ErrnoException).code;
    if (code === 'ERR_CRYPTO_ECDH_INVALID_PUBLIC_KEY') {
      return {
        state: makeFailed(0x02, "device's Public Key is not a valid point on P-256 (Section 5.4.2.3)"),
        send: [],
      };
    }
    throw err;
  }

  const confSalt = confirmationSalt(
    state.inviteValue,
    state.capabilitiesValue,
    state.startValue,
    state.ephemeralKeyPair.publicKey,
    publicKeyDevice,
  );
  const confKey = confirmationKey(ecdhSecret, confSalt);
  const ownConfirmation = confirmationValue(confKey, state.randomProvisioner, NO_OOB_AUTH_VALUE);

  const confirmationPdu: ProvisioningConfirmation = { type: 'confirmation', confirmation: ownConfirmation };

  // Section 5.4.2.3: "After the ECDHSecret is computed, the Provisioner
  // ... shall delete its private-public key pair" - `ephemeralKeyPair`
  // (private key included) is not carried into this next state.
  const nextState: AwaitingConfirmationDeviceState = {
    phase: 'awaitingConfirmationDevice',
    randomProvisioner: state.randomProvisioner,
    provisioningData: state.provisioningData,
    ecdhSecret,
    confirmationSaltValue: confSalt,
    confirmationKeyValue: confKey,
    ownConfirmation,
  };
  return { state: nextState, send: [encodeProvisioningPdu(confirmationPdu)] };
}

function onConfirmationDevice(state: AwaitingConfirmationDeviceState, pdu: Buffer): ProvisioningStepResult {
  const outcome = decodeOrFail(pdu);
  if ('failed' in outcome) return { state: outcome.failed, send: [] };
  const decoded = outcome.decoded;
  if (decoded.type !== 'confirmation') {
    return { state: unexpectedType('Confirmation', decoded.type), send: [] };
  }
  if (decoded.confirmation.length !== CONFIRMATION_LENGTH) {
    return {
      state: makeFailed(
        0x02,
        `device Confirmation is ${decoded.confirmation.length} bytes, expected ${CONFIRMATION_LENGTH} under BTM_ECDH_P256_CMAC_AES128_AES_CCM`,
      ),
      send: [],
    };
  }

  // Section 5.4.2.4.2: "the Provisioner ... shall compare the
  // ConfirmationProvisioner and the ConfirmationDevice values. ... If the
  // values are equal, the provisioning protocol shall fail" (the second
  // ellipsis stands for the source's own "if not equal" bullet, the
  // ordinary case - see the module header's note on this) - checked
  // before anything else.
  if (decoded.confirmation.equals(state.ownConfirmation)) {
    return {
      state: makeFailed(0x04, "device's ConfirmationDevice equals the provisioner's own ConfirmationProvisioner (Section 5.4.2.4.2)"),
      send: [],
    };
  }

  const randomPdu: ProvisioningRandom = { type: 'random', random: state.randomProvisioner };

  const nextState: AwaitingRandomDeviceState = {
    phase: 'awaitingRandomDevice',
    randomProvisioner: state.randomProvisioner,
    provisioningData: state.provisioningData,
    ecdhSecret: state.ecdhSecret,
    confirmationSaltValue: state.confirmationSaltValue,
    confirmationKeyValue: state.confirmationKeyValue,
    confirmationDevice: decoded.confirmation,
  };
  return { state: nextState, send: [encodeProvisioningPdu(randomPdu)] };
}

function onRandomDevice(state: AwaitingRandomDeviceState, pdu: Buffer): ProvisioningStepResult {
  const outcome = decodeOrFail(pdu);
  if ('failed' in outcome) return { state: outcome.failed, send: [] };
  const decoded = outcome.decoded;
  if (decoded.type !== 'random') {
    return { state: unexpectedType('Random', decoded.type), send: [] };
  }
  if (decoded.random.length !== RANDOM_LENGTH) {
    return {
      state: makeFailed(
        0x02,
        `device Random is ${decoded.random.length} bytes, expected ${RANDOM_LENGTH} under BTM_ECDH_P256_CMAC_AES128_AES_CCM`,
      ),
      send: [],
    };
  }

  // Section 5.4.2.4.2: "When the Provisioner receives the Provisioning
  // Random PDU from the Provisionee, it shall compute the
  // ConfirmationDevice value by using the received RandomDevice value." ...
  // "If the ConfirmationDevice value received is not equal to the
  // computed ConfirmationDevice, the provisioning protocol shall fail."
  // (the ellipsis stands for the source's own intervening "if equal"
  // bullet, the ordinary successful case). THIS is the check the brief's
  // mutation step targets: a machine that
  // accepts `decoded.random` without this comparison can never detect a
  // forged confirmation.
  const recomputedConfirmationDevice = confirmationValue(state.confirmationKeyValue, decoded.random, NO_OOB_AUTH_VALUE);
  if (!recomputedConfirmationDevice.equals(state.confirmationDevice)) {
    return {
      state: makeFailed(
        0x04,
        'ConfirmationDevice recomputed from the received RandomDevice does not match the value received earlier (Section 5.4.2.4.2: the Provisionee is not authenticated)',
      ),
      send: [],
    };
  }

  const salt = provisioningSalt(state.confirmationSaltValue, state.randomProvisioner, decoded.random);
  const sessionKeyValue = sessionKey(state.ecdhSecret, salt);
  const sessionNonceValue = sessionNonce(state.ecdhSecret, salt);
  const deviceKeyValue = deriveDeviceKey(state.ecdhSecret, salt);

  const plaintext = Buffer.concat([
    state.provisioningData.netKey,
    encodeUInt16BE(state.provisioningData.netKeyIndex),
    Buffer.from([state.provisioningData.flags]),
    encodeUInt32BE(state.provisioningData.ivIndex),
    encodeUInt16BE(state.provisioningData.unicastAddress),
  ]);
  const { ciphertext, tag } = ccmEncrypt(sessionKeyValue, sessionNonceValue, plaintext, DATA_MIC_LENGTH);
  const dataPdu: ProvisioningData = { type: 'data', encryptedProvisioningData: ciphertext, mic: tag };

  const nextState: AwaitingCompleteState = { phase: 'awaitingComplete', deviceKeyValue };
  return { state: nextState, send: [encodeProvisioningPdu(dataPdu)] };
}

function onComplete(state: AwaitingCompleteState, pdu: Buffer): ProvisioningStepResult {
  const outcome = decodeOrFail(pdu);
  if ('failed' in outcome) return { state: outcome.failed, send: [] };
  const decoded = outcome.decoded;
  if (decoded.type !== 'complete') {
    return { state: unexpectedType('Complete', decoded.type), send: [] };
  }
  return { state: { phase: 'provisioned', deviceKey: state.deviceKeyValue }, send: [] };
}
